### ISSUE TITLE
setToken function is not working

### ISSUE THREAD

**Issue by EpicIvo** [nordigen/nordigen-node#1]
**Describe the bug**
The `setToken` function doesn't seems to work for me. I'm running into the following error:

`TypeError: client.setToken is not a function`.

**To Reproduce**
1. I just copied the Quickstart code.

**Expected behavior**
I expect the function to work.

**Screenshots**
\-

**Additional context**
No fancy things, just a clean Node.js project. The other functions do work for me.

**Comment by victory-sokolov** [comment]
Hi, thank you for creating an issue.
Seems like it is a mistake in our quickstart guide.

`setToken` is not a method but a setter, so you could try to set token like so

`client.token = "YOUR_TOKEN"`

**Comment by EpicIvo** [comment]
Yes, that works. Thanks!
