### ISSUE TITLE
Error while Nordigen node client library on node version > 12.x : Must use import to load ES Module: /../node_modules/nordigen-node/lib/index.js require() of ES modules is not supported.

### ISSUE THREAD

**Issue by praji1304** [nordigen/nordigen-node#13]
I am using latest stable node version i.e 16.14.2, I get below mentioned error on compiling the code.

_const nordigen_node_1 = require("nordigen-node");
                        ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/polyscripts/polyscripts/payments-backend/node_modules/nordigen-node/lib/index.js from /home/../dist/nordigen/nordigen.controller.js not supported.
Instead change the require of index.js in /home/../dist/nordigen/nordigen.controller.js to a dynamic import() which is available in all CommonJS modules._

**Comment by victory-sokolov** [comment]
Hi.

You should use ``import NordigenClient from "nordigen-node";`` instead of `require`

As well you will need to add `"type": "module",` to package.json

You can check `express` example app in the `example` directory

**Comment by praji1304** [comment]
Hi @victory-sokolov ,

Thanks for the quick reply,

I followed the same approach as importing NordigenClient from "nordigen-node". I'am using nestJs and the code I write is in typescript. Hence the error that is being thrown is in the transpiled .js file, that I do not have any control over. 
On doing so I got an error mentioned below:Must use import to load ES Module: /home/../node_modules/nordigen-node/lib/index.js
require() of ES modules is not supported.

Aslo about adding "type": "module" to package.json, on trying that I got an error as attached in the screenshot.
well I surfed on internet for further resolution, but few say index.js should be renamed to index.cjs, but I am not sure how and where that would affect the whole application. 

![nordigenIssue](https://user-images.githubusercontent.com/102822749/161340077-c25c1ced-e4f8-42f3-8763-1a9965bbdb4f.png)

**Comment by deyceg** [comment]
If you want to use commonjs you can run the module through babel and it'll work.

**Comment by jans-y** [comment]
@praji1304 Could you please share your solution? I am still stuck on it. Also using NestJS.

Thanks

**Comment by praji1304** [comment]
@jans-y  did not find any solution that time at least, I ended up implementing the integration with their APIs. It will cost you a day but work perfectly fine.

**Comment by jan-siroky** [comment]
@praji1304 Thanks for the response. I did the same. Would be nice to either have it fixed or state this into docs as known limitation so devs don't waste their time on this issue ;)

**Comment by fstybel** [comment]
> If you want to use commonjs you can run the module through babel and it'll work.

Can you explain how to do it?

**Comment by victory-sokolov** [comment]
Hello! 
Sorry for the delay in response.
You could try to use dynamic-imports to overcome this problem.

Try something like this and let us know if this will works for you

```js
const nordigenNode = await import('nordigen-node');
const NordigenClient = nordigenNode.default;
const client = new NordigenClient({secretId: '', secretKey: ''}); 
```
