### ISSUE TITLE
Incorrect order of transactions

### ISSUE THREAD

**Issue by gillsoftab** [nordigen/nordigen-node#23]
**Describe the bug**
Transactions are not ordered in the correct order on the same day when compared to the bank statement list.

**To Reproduce**
1. Use [getTransactions](https://github.com/nordigen/nordigen-node/blob/4dff7984093f45a0ae7cbdbae3e1f8ac4a6e5c4a/lib/api/account.js#L81) call from AccountAPI.
2. Specify dateFrom and dateTo parameters as intended.
3. Transactions on the same date are not in the correct order compared to the order in the bank statement list. The current behavior is nondeterministic and might or might not be in the correct order for a single request.

**Expected behavior**
Transactions should always be ordered in the exact same order as in the bank statement list.

**Comment by safriks** [comment]
Hi @gillsoftab ,

Aleks from Nordigen Support here.
Yes, transactions are returned in non-deterministic order. As banks handle transaction order in a variety of ways, we cannot rely on them to return transaction in some specific order.
Sorry, can't help you right now.

In the mid-term we are working on some improvements in how we handle data, so one might expect some improvements in winter or next year. 

Hope you can work around this one.

Cheers, 
Aleks

**Comment by gillsoftab** [comment]
Ok, thanks for the answer.
We suspected it might be the banks that does this.

It will be the same balance per day but with transactions in the wrong order.
