### ISSUE TITLE
Can't solve "Cannot use import statement outside a module" 

### ISSUE THREAD

**Issue by sebastiankunn** [nordigen/nordigen-node#34]
**Describe the bug**
When testing with jest it displays "Cannot use import statement outside a module" 

**To Reproduce**
I added the library with npm install nordigen-node --save, wrote code to substitute direct API calls with the methods in the library as the quickstart guide showed, called them in my code and then proceeded in testing the files.

**Expected behavior**
I expected to solve this error by either adding type:module to package.json, installing babel/nodemon, or in general by specifying that the library must not be executed as a commonjs, but nothing solves the error

**Screenshots**
![immagine](https://user-images.githubusercontent.com/100591083/204534743-7dde427e-1033-4ccb-9c78-9fe2cf97edf5.png)

**Comment by moioo91120** [comment]
I have exactly the same problem, running in a node backend with typescript (nrwl + nestjs).

**Comment by victory-sokolov** [comment]
This issues is caused because of node-fetch starting from v3 is using only ESM modules, we replaced it with axios, could you try it again with the latest library version

**Comment by conor-deegan** [comment]
Hey @victory-sokolov , trying it with `1.2.1` and having the same issue.

**Comment by jannikhst** [comment]
How can it take more than 3 Months to fix this issue?
Just use my fork or create your own fork and copy my last two commits...
`npm install jannikhst/nordigen-node`

**Comment by conor-deegan** [comment]
@victory-sokolov Is there any update on this issue?

Happy to use @jannikhst fork for now but would be ideal to get this fixed.

**Comment by ShivPool** [comment]
Hi Nordigen Team - I've got my main developer completely stuck with this and as I understand it, it's a ten min fix at your end. Before we move over to Plaid, can we get a positive response that someone will be fixing this in the the next 48hrs pls?

**Comment by victory-sokolov** [comment]
@conor-deegan @ShivPool @sebastiankunn 
Sorry for the delay. We've made a fix, could please try with latest version 1.2.2

**Comment by ShivPool** [comment]
Oh wow thank you Viktor! Conor will work on installation asap.
———————————
Shiv Malik
CEO
pooldata.io
+44 7843 248 134

———————————
Data For Everyone

**Comment by conor-deegan** [comment]
@victory-sokolov , thank you.

There seems to be a small bug with accessing the types. 

In current package.json, types is declared as:

```
"types": "dist/index.d.ts",
```

This leads to 'Could not find a declaration file for module 'nordigen-node'. '/Users/username/project/node_modules/nordigen-node/dist/index.cjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/nordigen-node` if it exists or add a new declaration (.d.ts) file containing `declare module 'nordigen-node';`'

However, updating your package.json to:

```
  "types": "dist/types/index.d.ts",
```

works. 

Could this be added?

**Comment by victory-sokolov** [comment]
@conor-deegan Thanks for noticing. Should be fixed now

**Comment by conor-deegan** [comment]
@victory-sokolov  Working. Thank you
