### ISSUE TITLE
Inconsistencies between `createRequisition` input type and API definition

### ISSUE THREAD

**Issue by sebelik** [nordigen/nordigen-node#39]
**Describe the bug**
In the type declaration for `createRequisition()` method input, the `reference`, `ssn`, `redirectImmediate` and `accountSelection` parameters are all required although the API does not enforce them.

**To Reproduce**
- (v 1.2.1) When constructing the input to `createRequisition()` method call, type checker will emit a warning
- When calling `POST ​/api​/v2​/agreements​/enduser​/` directly via curl without these parameters, the API returns a successful response

**Expected behavior**
`reference`, `ssn`, `redirectImmediate`, `accountSelection` should either be marked optional in the type declaration or the API should enforce these parameters.

**Comment by victory-sokolov** [comment]
Hi! Thank for noticing it, should be fixed with `1.2.2` release.
