### ISSUE TITLE
Account balance for specific day

### ISSUE THREAD

**Issue by Janjiran** [nordigen/nordigen-node#42]
Right now, you can get account balance only for the current day AFAIK.

Ok solution would be to add `date` parameter to API call.
The best solution would be to add date-range like `dateFrom` and `dateTo` for which the API would return balances for each day.

The only workaround I can think of is to get todays balance + transactions from today to that specific day and add/subtract each transaction from the current balance however that's not really a great solution, especially if the specific day is far from today.

**Comment by safriks** [comment]
Hi @Janjiran,

Unfortunately that's impossible - vast majority of banks don't return balances for specific days, just on the day of request.
But some do provide balance after each transactions. More in the faq: https://nordigen.zendesk.com/hc/en-gb/articles/7670566178717-How-to-calculate-balance-after-transactions-

Hope this helps somewhat.

Regards,
Aleks
Bank Account Data Support Lead
