### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by jorisre** [nordigen/nordigen-node#45]
**Is your feature request related to a problem? Please describe.**
Migrate the repo to TypeScript and benefits of all its advantages (I noticed the types are currently wrong)

**Describe the solution you'd like**
Migrate the repo to TypeScript

**Describe alternatives you've considered**
None

**Additional context**
I'm opened to do that migration

**Comment by mathieumagalhaes** [comment]
I'm also currently bumping into this issue.
More specifically:

```
node_modules/nordigen-node/dist/types/api/account.d.ts(53,48): error TS2339: 
Property 'country' does not exist on type '{ dateFrom: string; dateTo: string; }'.
```

_And_ 

```
node_modules/nordigen-node/dist/types/index.d.ts(8,40): error TS2339: 
Property 'baseUrl' does not exist on type '{ secretId: string; secretKey: string; }'.
```
