### ISSUE TITLE
Migration to GoCardLess

### ISSUE THREAD

**Issue by MatissJanis** [nordigen/nordigen-node#49]
:wave:

Hi! Not exactly sure if this is a feature request or bug report.

Given that Nordigen was acquired by GoCardLess and is now fully moving under their umbrella - is there a migration path/guide for existing `nordigen-node` customers?

Thanks

**Comment by matt-podsiadlo** [comment]
Hi @victory-sokolov , are you planning to release 1.2.5 to [npm](https://www.npmjs.com/package/nordigen-node)? As it stands right now, 1.2.4 is broken due to incorrect URLs.

**Comment by victory-sokolov** [comment]
Hi @MatissJanis release 1.2.5 was published to npm
