### ISSUE TITLE
Will you publish the addition of Typescript types to npm?

### ISSUE THREAD

**Issue by EpicIvo** [nordigen/nordigen-node#9]
**Is your feature request related to a problem? Please describe.**
\-

**Describe the solution you'd like**
I saw that you merged my addition of Typescript types 😄. I was wandering when you would publish these to npm so that I can start using them in my project.

**Describe alternatives you've considered**
\-

**Additional context**
Btw I've also added the command: `npm run gen:types` to generate the types from the source code. So whenever you make a change to the project in the future, please make sure to run this command before you commit the changes 🙂.

**Comment by victory-sokolov** [comment]
Hi! Sorry for the delay.
We've just published a new version. Could you please verify if the types are working?

Thank You.

**Comment by EpicIvo** [comment]
Hi! Sorry for the delayed response.
The new version including the types works, thank you very much for publishing it!

Cheers
